# Site settings
title: Riverscapes Documentation
description: > # this means to ignore newlines until "baseurl:"
  Some site description will go here
url: http://riverscapes.northarrowresearch.com/
baseurl: ""

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"


layouts_dir:  src/_layouts
includes_dir: src/_includes

exclude:
  - src
  - LICENSE
  - README.md
  - _config.yml